name: GitHub Actions Demo
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create File .env
        run: |
          echo some data > .env
      - name: Create File
        run: |
          echo some data > .env.db
      - name: Show file content
        run: |
          pwd
          ls -la
          cat .env.db
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker-compose exec -T web pytest
      - name: PreCommit install
        run: docker-compose exec poetry add black pylint mypy
      - run: docker-compose exec black --diff --check $(git ls-files '*.py')
      - run: docker-compose exec pylint --disable=all --enable=unused-import $(git ls-files '*.py')
      - run: docker-compose exec mypy --strict $(git ls-files '*.py')